import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:bonkano_meet_pro/utils/app_common.dart';
import '../model/chat_message_model.dart';
import 'package:path/path.dart' as p;

class ChatService {
  FirebaseFirestore get _firestore => FirebaseFirestore.instanceFor(
      app: Firebase.app(), databaseId: 'baseneurocarekivi');
  FirebaseStorage get _storage => FirebaseStorage.instanceFor(
      bucket: 'kivicareneurocare.firebasestorage.app');

  // Récupérer les messages liés à un Rendez-vous (appointmentId)
  Stream<List<ChatMessage>> getMessages(int appointmentId) {
    return _firestore
        .collection('chats')
        .doc(appointmentId.toString())
        .collection('messages')
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs.map((doc) => ChatMessage.fromMap(doc.data(), doc.id)).toList();
    });
  }

  // Envoyer un message Texte depuis le Docteur
  Future<void> sendMessage(int appointmentId, String text, int receiverId) async {
    final currentUserId = loginUserData.value.id; // L'Id du Docteur (Admin/Receptionist/Doctor)

    ChatMessage message = ChatMessage(
      id: '', // Generated by Firestore
      appointmentId: appointmentId,
      senderId: currentUserId,
      receiverId: receiverId,
      text: text,
      timestamp: DateTime.now(), // Fallback before server timestamp
    );

    await _firestore
        .collection('chats')
        .doc(appointmentId.toString())
        .collection('messages')
        .add(message.toMap());
  }

  // Envoyer une image
  Future<void> sendImageMessage(int appointmentId, File imageFile, int receiverId) async {
    final senderId = loginUserData.value.id;
    final roomId = appointmentId.toString();
    int timestamp = DateTime.now().millisecondsSinceEpoch;
    String extension = p.extension(imageFile.path);

    Reference storageRef = _storage.ref().child('chats/$appointmentId/$timestamp$extension');

    try {
      // Upload de l'image
      UploadTask uploadTask = storageRef.putFile(imageFile);
      TaskSnapshot snapshot = await uploadTask;
      String downloadUrl = await snapshot.ref.getDownloadURL();

      ChatMessage message = ChatMessage(
        id: '',
        appointmentId: appointmentId,
        text: "📷 Image",
        senderId: senderId,
        receiverId: receiverId,
        timestamp: DateTime.now(),
        imageUrl: downloadUrl,
      );

      // Mettre à jour la chambre
      await _firestore.collection('chats').doc(roomId).set({
        'appointmentId': appointmentId,
        'patientId': receiverId,
        'doctorId': senderId,
        'lastMessage': "📷 Image",
        'lastTimestamp': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      }, SetOptions(merge: true));

      // Ajouter le message
      await _firestore
          .collection('chats')
          .doc(roomId)
          .collection('messages')
          .add(message.toMap());
    } catch (e) {
      throw 'Erreur lors de l\'envoi de l\'image : $e';
    }
  }

  // Envoyer un document
  Future<void> sendDocumentMessage(int appointmentId, File documentFile, int receiverId, String originalFileName) async {
    final senderId = loginUserData.value.id;
    final roomId = appointmentId.toString();
    int timestamp = DateTime.now().millisecondsSinceEpoch;

    Reference storageRef = _storage.ref().child('chats/$appointmentId/documents/${timestamp}_$originalFileName');

    try {
      // Upload du document
      UploadTask uploadTask = storageRef.putFile(documentFile);
      TaskSnapshot snapshot = await uploadTask;
      String downloadUrl = await snapshot.ref.getDownloadURL();

      ChatMessage message = ChatMessage(
        id: '',
        appointmentId: appointmentId,
        text: "📄 Fichier joint : $originalFileName",
        senderId: senderId,
        receiverId: receiverId,
        timestamp: DateTime.now(),
        documentUrl: downloadUrl,
      );

      // Mettre à jour la chambre
      await _firestore.collection('chats').doc(roomId).set({
        'appointmentId': appointmentId,
        'patientId': receiverId, // assuming patient is receiver
        'doctorId': senderId,
        'lastMessage': "📄 Fichier",
        'lastTimestamp': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      }, SetOptions(merge: true));

      // Ajouter le message
      await _firestore
          .collection('chats')
          .doc(roomId)
          .collection('messages')
          .add(message.toMap());
    } catch (e) {
      throw 'Erreur lors de l\'envoi du document : $e';
    }
  }
}
