// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return android; // Use Android config for Windows desktop testing
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

static const FirebaseOptions android = FirebaseOptions(
  appId: "1:214738954591:ios:4e0802e08779ddc75f6eea",
  apiKey: 'AIzaSyCBwddeG80wz19VNhbQ7rl6bDq49csTgNo',
  projectId: 'kivicareneurocare',
  messagingSenderId: '214738954591',
  storageBucket: 'kivicareneurocare.firebasestorage.app',
);

static const FirebaseOptions ios = FirebaseOptions(
  appId: "FIREBASE iOS APP ID",
  apiKey: 'FIREBASE API KEY',
  projectId: 'kivicareneurocare',
  messagingSenderId: '214738954591',
  storageBucket: 'kivicareneurocare.firebasestorage.app',
  iosBundleId: 'com.neurocareconnect.telemed',
);
}
